min_protovend_version: 5.0.2
vendor:
- branch: master
  host: github.skyscannertools.net
  repo: adverts/ads-retrieval-service
  root: ''
- branch: master
  host: github.skyscannertools.net
  repo: adverts/delivery-service
  root: ''
- branch: master
  host: github.skyscannertools.net
  repo: bamboo/xsell-v2
  root: ''
- branch: master
  host: github.skyscannertools.net
  repo: can-i-go/travel-restrictions
  root: ''
- branch: master
  host: github.skyscannertools.net
  repo: car-hire-web/mangalica
- branch: master
  host: github.skyscannertools.net
  repo: dps/conductor
- branch: master
  host: github.skyscannertools.net
  repo: dps/fare-attributes-svc
- branch: master
  host: github.skyscannertools.net
  repo: flexible-search/alternatives-inventory
- branch: master
  host: github.skyscannertools.net
  repo: flight-search/fare-policies
- branch: main
  host: github.skyscannertools.net
  repo: flux-capacitor/taps-api
  root: ''
- branch: master
  host: github.skyscannertools.net
  repo: fps/flights-pricing-svc
- branch: master
  host: github.skyscannertools.net
  repo: hotels-backend/bellboy
  root: ''
- branch: master
  host: github.skyscannertools.net
  repo: martech/postcard
  root: ''
- branch: main
  host: github.skyscannertools.net
  repo: spyro/baggage-plugin
- branch: master
  host: github.skyscannertools.net
  repo: spyro/grimm
- branch: main
  host: github.skyscannertools.net
  repo: spyro/simple-messages-plugin
  root: ''
- branch: master
  host: github.skyscannertools.net
  repo: terra/green-itineraries-schema
  root: ''
- branch: master
  host: github.skyscannertools.net
  repo: unified-search/unified-search-service
